### ISSUE TITLE
Create prototype UI design

### ISSUE THREAD

**Issue by akuksin** [noetl/noetl-ui#1]
Create prototype UI design of https://github.com/noetl/noetl/wiki/Config-proposal.md

**Comment by Sergo007** [comment]
![image](https://user-images.githubusercontent.com/10484588/46033917-0c983180-c108-11e8-96e9-0baf04876ddc.png)

**Comment by antonputra** [comment]
@akuksin @Sergo007 why do we have duplicate project 
https://github.com/noetl/noetl-ui/projects/1?

**Comment by antonputra** [comment]
@akuksin can we close this issue?
